### ISSUE TITLE
Login page backend aka connection to linux

### ISSUE THREAD

**Issue by tmkkcc** [pwn-ble/pwnable#35]

**Comment by averywald** [comment]
yes im gonna figure this out asap

**Comment by averywald** [comment]
got login service working [with this commit](https://github.com/pwn-ble/pwnable/commit/c442d83b3a9d0332b146048c455dc1db5abc6a41). it needs to be brought into the login UI tkinter process. Right now it is running from `src/app.py` after it calls the login UI as a subprocess, so it waits for that to finish, and passes the login credentials by printing them to console, then they are captured by subprocess' stdout PIPE.  this needs to be changed, possibly by running the service in `src/gui/login.py`; maybe by writing a temp file then opening that.

either way process management needs to be handled by a service so that processes are embedded where they are needed, and no awkward handoffs happen between them.
